music={
    "gehra":"https://www.youtube.com/watch?v=jr7WLWxL1ac&list=RDjr7WLWxL1ac&start_radio=1",
    "kunfaya":"https://www.youtube.com/watch?v=27CBPR7CSks&list=RD27CBPR7CSks&start_radio=1",
    "believer":"https://www.youtube.com/watch?v=W0DM5lcj6mw&list=RDW0DM5lcj6mw&start_radio=1",
    "let me down slowly":"https://www.youtube.com/watch?v=jLNrvmXboj8&list=RDjLNrvmXboj8&start_radio=1",
    "lollipop":"https://www.youtube.com/watch?v=QQUBrXUAxSs&list=RDQQUBrXUAxSs&start_radio=1",
    "dilwar":"https://www.youtube.com/watch?v=TRa9IMvccjg&list=RDTRa9IMvccjg&start_radio=1",
    "mujhko rana jii maf karna":"https://www.youtube.com/watch?v=HVYJD68_VOI&list=RDHVYJD68_VOI&start_radio=1",
    "fevicol":"https://www.youtube.com/watch?v=zE7Pwgl6sLA&list=RDzE7Pwgl6sLA&start_radio=1",
    "aaj ki rat":"https://www.youtube.com/watch?v=hxMNYkLN7tI&list=RDhxMNYkLN7tI&start_radio=1",
    "jeene laga hu":"https://www.youtube.com/watch?v=qpIdoaaPa6U&list=RDqpIdoaaPa6U&start_radio=1",
    "bulleya":"https://www.youtube.com/watch?v=_51KXfwcPMs&list=RDGMEM916WJxafRUGgOvd6dVJkeQ&start_radio=1&rv=qpIdoaaPa6U",
    "tum jo aaye":"https://www.youtube.com/watch?v=kTXilT_KbUM&list=RDGMEM916WJxafRUGgOvd6dVJkeQ&index=9",
    "ishk sufiyana":"https://www.youtube.com/watch?v=5RT6QMKJTjQ&list=RDGMEM916WJxafRUGgOvd6dVJkeQ&index=14",
    "afghan jalebi":"https://www.youtube.com/watch?v=zC3UbTf4qrM&list=RDGMEM916WJxafRUGgOvd6dVJkeQ&index=22",
    "mai rang sharbaton ka":"https://www.youtube.com/watch?v=RBCk1SyC1PA&list=RDGMEM916WJxafRUGgOvd6dVJkeQ&index=37",
    "tere vaste":"https://www.youtube.com/watch?v=g5WZLO8BAC8&list=RDGMEM916WJxafRUGgOvd6dVJkeQ&index=46",
    "waka waka":"https://www.youtube.com/watch?v=pRpeEdMmmQ0&list=RDpRpeEdMmmQ0&start_radio=1",
    "give me some sunshine":"https://www.youtube.com/watch?v=lbCRtrrMvSw&list=RDlbCRtrrMvSw&start_radio=1",
    "why this colaveri di":"https://www.youtube.com/watch?v=YR12Z8f1Dh8&list=RDYR12Z8f1Dh8&start_radio=1",
    "chammak challo":"https://www.youtube.com/watch?v=ufHLYw9q7vQ&list=RDufHLYw9q7vQ&start_radio=1",
    "zallima":"https://www.youtube.com/watch?v=gTXiALHJPBU&list=RDgTXiALHJPBU&start_radio=1",
    "sanam teri kasam":"https://www.youtube.com/watch?v=kKljXVVkgS4&list=RDkKljXVVkgS4&start_radio=1",
    "dil meri na sune":"https://www.youtube.com/watch?v=Z-ku_0b-70w&list=RDZ-ku_0b-70w&start_radio=1",
    "all is well":"https://www.youtube.com/watch?v=7PzwOiW8-n0&list=RD7PzwOiW8-n0&start_radio=1",
    "choli ke piche kya hai":"https://www.youtube.com/watch?v=sTY1aQ3hruA&list=RDsTY1aQ3hruA&start_radio=1",
    "chal chhaiya chhaiya":"https://www.youtube.com/watch?v=4eDUrRb7ono&list=RD4eDUrRb7ono&start_radio=1",
    "kajra re":"https://www.youtube.com/watch?v=tGv6Ce9mMWA&list=RDtGv6Ce9mMWA&start_radio=1",
    "koun tujhe":"https://www.youtube.com/watch?v=Ov0YGGSY6gY&list=RDOv0YGGSY6gY&start_radio=1",
    "sanam re":"https://www.youtube.com/watch?v=DS-raAyMxl4&list=RDDS-raAyMxl4&start_radio=1",
    "teri meri kahani":"https://www.youtube.com/watch?v=fPc7UxB0BEE&list=RDfPc7UxB0BEE&start_radio=1",
    "tuhi mera":"https://www.youtube.com/watch?v=yBa3FVQKAvY&list=RDyBa3FVQKAvY&start_radio=1",
    "ishk mubarak":"https://www.youtube.com/watch?v=V1oczq_8L0E&list=RDV1oczq_8L0E&start_radio=1",
    "hua hai aaj pehli bar":"https://www.youtube.com/watch?v=DGVJtAHzzDQ&list=RDDGVJtAHzzDQ&start_radio=1",
    "humnawa mere":"https://www.youtube.com/watch?v=TmRgK-pXH9c&list=RDTmRgK-pXH9c&start_radio=1",
    "janam janam":"https://www.youtube.com/watch?v=pIBoAh4OXhQ&list=RDpIBoAh4OXhQ&start_radio=1",
    "kamli":"https://www.youtube.com/watch?v=YrrDrx5Rd_I&list=RDYrrDrx5Rd_I&start_radio=1",
    "aaye ho meri jindagi me":"https://www.youtube.com/watch?v=CbFjVMEZA5k&list=RDCbFjVMEZA5k&start_radio=1",
    "mera yar mila de":"https://www.youtube.com/watch?v=EiueuBPAzw8&list=RDEiueuBPAzw8&start_radio=1",
    "dulhe ka sehra":"https://www.youtube.com/watch?v=OepOwnY_gvU&list=RDOepOwnY_gvU&start_radio=1",
    "dil laga liya":"https://www.youtube.com/watch?v=CHRMRsVu4do&list=PL5_sBVYPxr-ark7RaArR-tLvvmm__TD1Q",
    "guzarish":"https://www.youtube.com/watch?v=T_QaWNTkXak&list=RDT_QaWNTkXak&start_radio=1",
    "tumhare hi rahenge hum":"https://www.youtube.com/watch?v=VjynoL4zEVw&list=RDVjynoL4zEVw&start_radio=1",
    "janiye":"https://www.youtube.com/watch?v=H1YR5rsScC8&list=RDH1YR5rsScC8&start_radio=1",
    "khuda jane":"https://www.youtube.com/watch?v=cmMiyZaSELo&list=RDcmMiyZaSELo&start_radio=1",
    "deewana deewana":"https://www.youtube.com/watch?v=IGti1RTS1wc&list=RDIGti1RTS1wc&start_radio=1"   
    
}